import OpenAI from "openai"; import fs from "node:fs/promises"; import path from "node:path";
import type { WebSurface } from "./surface.js"; import { AgentDecisionSchema, CapabilitySchema, type AgentDecision, type Step } from "./schema.js"; import { enforcePolicy } from "./policy.js"; import { RunLogger } from "./logger.js";
export interface DecisionProvider { decide(goal:string, observation:{url:string;title:string;accessibility:string}, history:AgentDecision[]):Promise<AgentDecision> }
export class OpenAIDecisionProvider implements DecisionProvider {
  private client=new OpenAI(); constructor(private model=process.env.OPENAI_MODEL??"gpt-5-mini"){}
  async decide(goal:string,o:{url:string;title:string;accessibility:string},history:AgentDecision[]):Promise<AgentDecision>{ const prompt=`You control a bank demo UI. Goal: ${goal}\nURL: ${o.url}\nAccessibility tree:\n${o.accessibility}\nHistory:${JSON.stringify(history)}\nChoose exactly one safe action. Prefer role/label/text locators. For invocation data, use the literal placeholder {{memberId}}, never a concrete ID. For a balance extraction the output name must be availableBalance, never the extracted value. After one extraction return done. Never invent elements.`; const r=await this.client.responses.create({model:this.model,input:prompt,text:{format:{type:"json_schema",name:"decision",strict:true,schema:{type:"object",additionalProperties:false,properties:{rationale:{type:"string"},action:{type:"string",enum:["click","fill","extract","done","escalate"]},locator:{anyOf:[{type:"object",additionalProperties:false,properties:{strategy:{type:"string",enum:["role","label","text","css","coordinates"]},value:{type:"string"},name:{type:["string","null"]},exact:{type:"boolean"},fallbacks:{type:"array",items:{type:"object",additionalProperties:false,properties:{strategy:{type:"string",enum:["role","label","text","css"]},value:{type:"string"},name:{type:["string","null"]}},required:["strategy","value","name"]}}},required:["strategy","value","name","exact","fallbacks"]},{type:"null"}]},value:{type:["string","null"]},output:{type:["string","null"]},success:{anyOf:[{type:"object",additionalProperties:false,properties:{kind:{type:"string",enum:["url","visible","text"]},value:{type:"string"}},required:["kind","value"]},{type:"null"}]}},required:["rationale","action","locator","value","output","success"]}}}}); const raw=JSON.parse(r.output_text); for(const k of ["locator","value","output","success"]) if(raw[k]===null) delete raw[k]; if(raw.locator?.name===null) delete raw.locator.name; for(const f of raw.locator?.fallbacks??[]) if(f.name===null) delete f.name; const parsed=AgentDecisionSchema.parse(raw); if(history.some(h=>h.action==="extract")) return {rationale:"Declared output extracted; goal complete",action:"done",success:{kind:"visible",value:"#account-loaded"}}; if(parsed.action==="extract") return {...parsed,output:"availableBalance"}; return parsed; }
}
export class ScriptedDecisionProvider implements DecisionProvider { private i=0; private seq:AgentDecision[]=[
  {rationale:"Enter parameter",action:"fill",locator:{strategy:"label",value:"Member number",exact:true,fallbacks:[]},value:"{{memberId}}"},
  {rationale:"Submit search",action:"click",locator:{strategy:"role",value:"button",name:"Find Member",exact:true,fallbacks:[]}},
  {rationale:"Open matching profile",action:"click",locator:{strategy:"role",value:"link",name:"Open Profile",exact:true,fallbacks:[]}},
  {rationale:"Open savings",action:"click",locator:{strategy:"role",value:"link",name:"Savings Account",exact:true,fallbacks:[]}},
  {rationale:"Read balance",action:"extract",locator:{strategy:"label",value:"Available balance",exact:true,fallbacks:[]},output:"availableBalance"},
  {rationale:"Goal complete",action:"done",success:{kind:"visible",value:"#account-loaded"}}
]; async decide(){return this.seq[this.i++]??{rationale:"No plan",action:"escalate"};}}
export async function discover(surface:WebSurface,provider:DecisionProvider,goal:string,baseUrl:string,outDir:string){
  const runId=`discovery-${Date.now()}`, log=new RunLogger(runId,path.join(outDir,"logs")), history:AgentDecision[]=[], steps:Step[]=[], outputs:Record<string,{type:"string"|"number"|"boolean";description:string}>={};
  await surface.page.goto(baseUrl); for(let i=0;i<12;i++){ const o=await surface.observe(); const d=await provider.decide(goal,{...o,accessibility:o.accessibility},history); history.push(d); log.record({phase:"discovery",step:i,decision:d,url:o.url}); if(d.action==="done"){ const artifact=CapabilitySchema.parse({schemaVersion:"1.0",capabilityVersion:"1.0.0",name:"lookup_savings_balance",description:"Look up a member and return the current savings balance",vendorApp:"heritage-core",baseUrl,approved:false,inputs:{memberId:{type:"string",required:true,sensitive:true}},outputs,steps,success:d.success??{kind:"visible",value:"#account-loaded"},businessOutcomes:[{code:"MEMBER_NOT_FOUND",locator:{strategy:"text",value:"No member was found",exact:false,fallbacks:[]},message:"No member exists for the supplied identifier"}],tenantOverrides:{},metadata:{createdAt:new Date().toISOString(),discoveredBy:provider.constructor.name}}); await fs.mkdir(path.join(outDir,"artifacts"),{recursive:true}); const ap=path.join(outDir,"artifacts","lookup-savings-balance.json"); await fs.writeFile(ap,JSON.stringify(artifact,null,2)); await log.save(); return {artifact,path:ap,runId}; }
    if(d.action==="escalate") throw new Error("HUMAN_REQUIRED: discovery provider requested intervention"); const step:Step={id:`step-${i+1}`,action:d.action,locator:d.locator,value:d.value,output:d.output,timeoutMs:5000,risk:"safe"}; enforcePolicy(surface.page.url(),step); const value=d.value?.replace("{{memberId}}","12345"); const extracted=await surface.act(step,value); if(d.output){ outputs[d.output]={type:d.output.toLowerCase().includes("balance")?"number":"string",description:`Extracted ${d.output}`}; log.record({output:d.output,value:extracted}); } steps.push(step); }
  throw new Error("HUMAN_REQUIRED: maximum discovery steps exceeded");
}
