import fs from "node:fs/promises"; import path from "node:path"; import type { WebSurface } from "./surface.js"; import { CapabilitySchema, type RunResult } from "./schema.js"; import { enforcePolicy } from "./policy.js"; import { RunLogger } from "./logger.js";
const resolve=(v:string|undefined,inputs:Record<string,unknown>)=>v?.replace(/\{\{(\w+)\}\}/g,(_,k)=>String(inputs[k]??""));
export async function replay(surface:WebSurface,raw:unknown,inputs:Record<string,unknown>,outDir:string):Promise<RunResult>{ const cap=CapabilitySchema.parse(raw), runId=`replay-${Date.now()}`, started=Date.now(), log=new RunLogger(runId,path.join(outDir,"logs"));
  for(const [k,s] of Object.entries(cap.inputs)) if(s.required && inputs[k]===undefined) return {status:"failure",runId,error:{category:"APP",stepId:"input",message:`Missing required input: ${k}`}};
  const outputs:Record<string,unknown>={}; await surface.page.goto(cap.baseUrl);
  for(const step of cap.steps){ try { enforcePolicy(surface.page.url(),step); log.record({phase:"replay",stepId:step.id,action:step.action}); const value=resolve(step.value,inputs); const x=await surface.act(step,value); if(step.output){ const spec=cap.outputs[step.output]; outputs[step.output]=spec?.type==="number"?Number(String(x).replace(/[^0-9.-]/g,"")):x; }
      for(const outcome of cap.businessOutcomes) if(await surface.locate(outcome.locator).count() && await surface.locate(outcome.locator).isVisible().catch(()=>false)){ const result={status:"business_outcome" as const,runId,code:outcome.code,message:outcome.message,stepId:step.id}; log.record({result}); await log.save(); return result; }
    } catch(e){ for(const outcome of cap.businessOutcomes) if(await surface.locate(outcome.locator).count() && await surface.locate(outcome.locator).isVisible().catch(()=>false)){ const result={status:"business_outcome" as const,runId,code:outcome.code,message:outcome.message,stepId:step.id}; log.record({result}); await log.save(); return result; } const dir=path.join(outDir,"failures",runId); await fs.mkdir(dir,{recursive:true}); const shot=path.join(dir,`${step.id}.png`); await surface.page.screenshot({path:shot,fullPage:true}); const msg=String(e); const category=msg.includes("POLICY")?"POLICY":msg.includes("Timeout")?"TIMEOUT":"LOCATOR"; const result={status:"failure" as const,runId,error:{category:category as "POLICY"|"TIMEOUT"|"LOCATOR",stepId:step.id,message:msg,evidence:shot}}; log.record({result}); await log.save(); return result; }}
  const checkpoint=cap.success.kind==="visible" ? await surface.page.locator(cap.success.value).isVisible().catch(()=>false) : cap.success.kind==="url" ? surface.page.url().includes(cap.success.value) : (await surface.page.locator("body").innerText()).includes(cap.success.value); if(!checkpoint) return {status:"failure",runId,error:{category:"CHECKPOINT",stepId:"success",message:`Checkpoint not met: ${cap.success.value}`}}; const result={status:"success" as const,runId,outputs,durationMs:Date.now()-started}; log.record({result}); await log.save(); return result; }
